INSERT INTO T_ASSOCIATIONKEY(game_id, key_name,from_date,end_date,create_by,create_time,update_by,update_time,cause,status)

VALUES(6235, '测试1',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1), 
(6235, '测试2',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1), 
(6235, '测试3',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2), 
(6236, '测试4',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',0), 
(6237, '测试5',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1), 
(6238, '测试6',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2), 
(6251, '测试7',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1), 
(6255, '测试8',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1), 
(6255, '测试9',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1), 
(6255, '测试10',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1), 
(6245, '测试11',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1), 
(6245, '测试12',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',0), 
(6225, '测试13',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2), 
(6235, '测试14',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1), 
(6235, '测试15',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1),
(6235, '测试16',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1);

INSERT INTO T_ASSOCIATIONKEY_GAME(key_id,game_id,game_name,from_date,end_date,create_by,create_time,update_by,update_time,cause,priority,status)
VALUES
(1,'6235', '欢乐斗地主',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1,1),
(1,'6234', '欢乐麻将',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1),
(1,'6233', '欢乐豆',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',3,0),
(1,'6232', '欢乐谷',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',4,2),
(1,'6235', '欢乐之家',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',5,1),
(2,'3347', '王者荣耀',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1,1),
(2,'3345', '荣耀王者',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1),
(2,'3346', '荣耀盒子',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',3,0),
(2,'3349', '王者之剑',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',4,2),
(3,'6224', '腾讯快运',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1,1),
(3,'6124', '腾讯QQ',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1),
(3,'6125', '腾讯微信',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',3,2),
(4,'6274', '穿越火线',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1,1),
(4,'6175', '穿越火线CF',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1),
(4,'6176', '腾讯穿越火线',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',3,2),   
(5,'6277', '地下城',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1,1),
(5,'6178', '地下城勇士',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1),
(5,'6179', '地下城勇士盒子',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',3,2),    
(6,'6273', '西游',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1,1),
(6,'6172', '西游记',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1),
(6,'6171', '梦幻西游',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',3,2),
(6,'6172', '天龙',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',3,2),
(7,'6280', '风云',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1,1),
(8,'6181', '风云之雄霸天下',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1),
(9,'6182', '拳皇',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',3,2),
(10,'6283', '拳皇1997',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1,1),
(11,'6184', '拳皇2003',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1),
(12,'6185', '三国',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',3,2),
(13,'6286', '三国英雄',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1,1),
(14,'6187', '三国志',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1),
(15,'6188', '三国群英战绩',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1,2),
(15,'6289', '三国杀',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1),
(16,'6190', '蜀山战纪',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',1,1),
(16,'6391', '仙剑奇缘',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1),
(16,'6392', '仙剑奇侠',now(),now(),'zhangguidong',now(),'zhangguidong',now(),'添加测试数据',2,1);
